# See https://github.com/coq-community/docker-coq-action#readme
name: Docker CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - 'coqorg/coq:8.17'
      max-parallel: 4
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - uses: coq-community/docker-coq-action@v1
        with:
          opam_file: 'coq-two-pcf-models.opam'
          install: |
            startGroup "Install dependencies"
              sudo apt-get update -y -q
              opam repo add iris-dev https://gitlab.mpi-sws.org/iris/opam.git
              opam pin add -n -y -k path $PACKAGE $WORKDIR
              opam update -y
              opam install --confirm-level=unsafe-yes -j 2 $PACKAGE --deps-only
            endGroup
          custom_image: ${{ matrix.image }}
